const categories = [
    "API management",
    "Analytics",
    "Bots",
    "Chat",
    "Code quality",
    "Code review",
    "Communication",
    "Continuous integration",
    "Customer Support",
    "Dependency management",
    "Deployment",
    "Design",
    "Developer Tools",
    "File Management",
    "Finance",
    "HR & Team Culture",
    "Health & Wellness",
    "IDEs",
    "Learning",
    "Localization",
    "Marketing",
    "Media & News",
    "Mobile",
    "Monitoring",
    "Office Management",
    "Productivity",
    "Project Management",
    "Project management",
    "Publishing",
    "Recently added",
    "Sales",
    "Security",
    "Security & Compliance",
    "Social & Fun",
    "Support",
    "Testing",
    "Travel",
    "Utilities",
    "Voice & Video"
]

module.exports = categories
